DROP DATABASE IF EXISTS peer_2_paws;
CREATE DATABASE peer_2_paws;
USE peer_2_paws;
DROP TABLE IF EXISTS Animals;
CREATE TABLE Animals (
  id INT AUTO_INCREMENT PRIMARY KEY,
  TypeName VARCHAR (64) NOT NULL,
  OwnerName VARCHAR (64) NOT NULL,
  OwnerEmail VARCHAR (128) NOT NULL,
  AnimalName VARCHAR (64) NOT NULL,
  Age INT NOT NULL,
  About VARCHAR (512) NOT NULL,
  ImageLink VARCHAR (1024) NULL,
  createdAt DATETIME NOT NULL,
  updatedAd DATETIME NOT NULL
);
DROP TABLE IF EXISTS EmailRecepients;
CREATE TABLE EmailRecepients (
  id INT AUTO_INCREMENT PRIMARY KEY,
  RecName VARCHAR (64),
  RecEmail VARCHAR (128),
  createdAt DATETIME NOT NULL,
  updatedAt DATETIME NOT NULL
)